

export const SET_SHOW_TIME = 'SET_SHOW_TIME';
export const SET_NO_TIME = 'SET_NO_TIME';
export const SET_TIME_STEP = 'SET_TIME_STEP';


export const SET_LOCATION_ID = 'SET_LOCATION_ID';
export const SET_LOCATION_NAME = 'SET_LOCATION_NAME';

export const PUSH_TEMPERATURE = 'PUSH_TEMPERATURE';
